'''
    The following are the strategic grams introduced in the paper 
    "Emergent Hierarchical Reasoning in LLMs through Reinforcement Learning"
     : https://arxiv.org/abs/2509.03646
'''

strategic_grams = [
    "## step", 
    "a good starting point is", 
    "a more direct approach is", 
    "a more straightforward approach", 
    "a simpler approach is", 
    "alright", 
    "alternatively", 
    "an alternative path is", 
    "an error in the thought process", 
    "analyze the", 
    "analyzing the given", 
    "and then find", 
    "another approach", 
    "are looking for", 
    "based on the given", 
    "break down the problem", 
    "break it down", 
    "break it down into manageable steps", 
    "but", 
    "but wait", 
    "but why", 
    "but without more information", 
    "can be rewritten as", 
    "can conclude that", 
    "can see that", 
    "check if", 
    "consider the case where", 
    "consider the properties of", 
    "correct the approach", 
    "define the variables", 
    "denote", 
    "determine how many", 
    "directly address the problem", 
    "does this hold true?", 
    "does this make sense?", 
    "double-checking the logic", 
    "finally need to", 
    "finally we need to", 
    "find a simpler", 
    "find a way to", 
    "find out how many", 
    "find the critical points", 
    "first need to", 
    "follow these steps", 
    "for simplicity", 
    "from earlier we have", 
    "from the above", 
    "from this, it follows that", 
    "from this, we can infer", 
    "given the complexity", 
    "given the complexity of", 
    "given the constraints", 
    "given the nature of", 
    "go back to the", 
    "goal is to", 
    "hmm,", 
    "hold on", 
    "however", 
    "however, we need to", 
    "i might have made an error", 
    "i need to re-evaluate", 
    "i should verify this result", 
    "identify the", 
    "identify the given information", 
    "if that doesn’t work, we can", 
    "if we consider", 
    "in a way that", 
    "in the context of", 
    "is there a simpler method?", 
    "is there a simpler way?", 
    "it logically follows that", 
    "it seems", 
    "it’s better", 
    "let me", 
    "let me pause and think", 
    "let me rethink this", 
    "let me verify", 
    "let’s", 
    "let’s analyze the possibilities", 
    "let’s assume", 
    "let’s backtrack", 
    "let’s break this down", 
    "let’s check our work", 
    "let’s check the constraints again", 
    "let’s consider another case", 
    "let’s denote", 
    "let’s double-check", 
    "let’s explore a different possibility", 
    "let’s formulate a plan", 
    "let’s go back a step", 
    "let’s outline the steps", 
    "let’s pause and think", 
    "let’s reconsider", 
    "let’s try a different angle", 
    "let’s validate this", 
    "looking back at the", 
    "maybe", 
    "maybe i can", 
    "my previous step was flawed", 
    "need to", 
    "need to account for", 
    "need to analyze", 
    "need to check", 
    "need to consider", 
    "need to count", 
    "need to determine", 
    "need to ensure", 
    "need to express", 
    "need to find", 
    "need to follow", 
    "need to identify", 
    "need to minimize",
    "need to reconsider", 
    "need to show", 
    "need to solve", 
    "need to think about", 
    "need to understand", 
    "need to use", 
    "next", 
    "note that", 
    "now", 
    "now let", 
    "now need to", 
    "now we need to", 
    "okay", 
    "on second thought",
    "on the other hand", 
    "one way to", 
    "our strategy is", 
    "perhaps", 
    "perhaps i can", 
    "problem is asking", 
    "problem states that", 
    "proceed with the following", 
    "rearrange the equation", 
    "recall that", 
    "referring to a previous step", 
    "revisiting the initial assumption", 
    "rewrite the equation", 
    "says that",
    "seems a bit complicated",
    "should consider", 
    "should focus on", 
    "should look for", 
    "similarly", 
    "simplify the problem", 
    "since", 
    "so", 
    "so after", 
    "so again", 
    "so the question becomes", 
    "so, yes", 
    "something is wrong here", 
    "specifically", 
    "start by", 
    "states that", 
    "step by step", 
    "step by step reasoning", 
    "step by step solution", 
    "step-by-step reasoning", 
    "that can’t be right", 
    "that seems", 
    "that was a mistake", 
    "that assumption was incorrect", 
    "the correct approach is", 
    "the core idea is", 
    "the first step is", 
    "the key insight is", 
    "the key is to realize", 
    "the key to solving this", 
    "the logical flow is", 
    "the next step is", 
    "the path to the solution", 
    "the plan is to", 
    "the problem asks for", 
    "the problem is about", 
    "the problem mentions", 
    "the problem says", 
    "the problem states", 
    "there is a mistake", 
    "there seems to be", 
    "therefore", 
    "think of this as", 
    "this allows us to", 
    "this approach isn’t working", 
    "this approach seems", 
    "this can be seen as", 
    "this implies", 
    "this implies that", 
    "this is because", 
    "this is not the correct approach", 
    "this isn’t leading anywhere", 
    "this leads to", 
    "this leads us to", 
    "this logically leads to", 
    "this means", 
    "this means that", 
    "this seems a bit", 
    "this suggests", 
    "this suggests a path", 
    "this suggests that", 
    "thus", 
    "to confirm", 
    "to consider the constraints", 
    "to determine", 
    "to do this", 
    "to ensure",
    "to ensure correctness", 
    "to find", 
    "to make it easier", 
    "to proceed", 
    "to see if", 
    "to solve this problem", 
    "to verify", 
    "try to", 
    "understand the given information", 
    "understanding the problem", 
    "understanding the problem first", 
    "upon closer inspection", 
    "use the concept of", 
    "use the fact", 
    "use the fact that", 
    "use the method of", 
    "use the properties of", 
    "verify the solution", 
    "wait", 
    "wait, but", 
    "wait, no", 
    "wait, that’s not right", 
    "want to find", 
    "we are dealing with", 
    "we can", 
    "we can approach this", 
    "we can conclude", 
    "we can deduce", 
    "we can infer", 
    "we can see", 
    "we can start by", 
    "we can think of this as", 
    "we can use", 
    "we know", 
    "what am i missing?", 
    "what happens if", 
    "what if we assume", 
    "what if we try", 
    "what is being asked", 
    "which means", 
    "will consider the", 
    "work our way"
]